// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzsetkjzcinbkaqofufy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6c2V0a2p6Y2luYmthcW9mdWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Nzg3MTgsImV4cCI6MjA2MzI1NDcxOH0.KBz0dLsODS1Jp3TiW_PSox9ZDE0N30Ln63gB_xFdLVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);